[project]
name = "modelcontextprotocolserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.4",
    "opencv-python>=4.11.0.86",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]
